[dependencies]
ipython = ">=8.0"
openssl = ">=3, <3.6"
datashader = ">=0.16"
holoviews = ">=1.18"
statsmodels = ">=0.14"
pillow = ">=10"
pip = "*"
ipywidgets = ">=8"
jupyterlab = ">=4"
sympy = ">=1.12"
xarray = ">=2023.9"
graphviz = ">=9"
numba = ">=0.59"
jupyter = ">=1.0"
widgetsnbextension = ">=4"
panel = ">=1.4"
scipy = ">=1.11"
openpyxl = ">=3.1"
jupyterlab_widgets = ">=3"
hvplot = ">=0.9"
netcdf4 = ">=1.6"
matplotlib = ">=3.8"
imageio = ">=2.34"
bokeh = ">=3.4"
pygraphviz = ">=1.11"
scikit-learn = ">=1.4"
libstdcxx = ">=3.4,<15.0"
cython = ">=3.0"
ipykernel = ">=6"
networkx = ">=3.2"
plotly = ">=5.18"
streamz = ">=0.6"
seaborn = ">=0.13"
colorcet = ">=3.1"
jinja2 = ">=3.1"
tqdm = ">=4.66"
libstdcxx-ng = ">=3.4,<15.0"
h5py = ">=3.10"
pandas = ">=2.1"
k3d = ">=2.16"
notebook = ">=7"
numpy = ">=1.26"
requests = ">=2.31"
scikit-image = ">=0.22"

    [dependencies.python]
    channel = "conda-forge"
    build = "*cp*"
    version = "3.12.*, >=3.10,!=3.14.0,!=3.14.1,<4"

[project]
name = ".CondaPkg"
platforms = ["linux-64"]
channels = ["conda-forge"]
channel-priority = "strict"
description = "automatically generated by CondaPkg.jl"
