import json
import os
import subprocess
import sys
import tempfile
from pathlib import Path


def notebook_to_script(notebook_path: Path) -> str:
    notebook = json.loads(notebook_path.read_text(encoding="utf-8"))
    cells = notebook.get("cells", [])
    code_cells = [cell for cell in cells if cell.get("cell_type") == "code"]
    if not code_cells:
        raise SystemExit(f"{notebook_path.name}: expected at least one code cell")

    parts = ["# Generated by docs/execute_notebook_smoke.py"]
    for cell in code_cells:
        source = "".join(cell.get("source", []))
        parts.append(source.rstrip())
    return "\n\n".join(parts) + "\n"


def main() -> None:
    if len(sys.argv) != 2:
        raise SystemExit("usage: execute_notebook_smoke.py <notebook.ipynb>")

    notebook_path = Path(sys.argv[1]).resolve()
    if not notebook_path.is_file():
        raise SystemExit(f"Notebook not found: {notebook_path}")

    repo_root = notebook_path.parents[3]
    script = notebook_to_script(notebook_path)
    env = os.environ.copy()

    with tempfile.NamedTemporaryFile("w", suffix=".jl", delete=False, encoding="utf-8") as handle:
        handle.write(script)
        temp_path = Path(handle.name)

    try:
        subprocess.run(
            ["julia", "--project=.", str(temp_path)],
            cwd=repo_root,
            env=env,
            check=True,
        )
    finally:
        temp_path.unlink(missing_ok=True)


if __name__ == "__main__":
    main()
