name: CI
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: only if it is a pull request build.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}
jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    permissions: # needed to allow julia-actions/cache to proactively delete old caches that it has created
      actions: write
      contents: read
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.10'
          - '1.12'
          - 'pre'
        os:
          - ubuntu-latest
        arch:
          - x64
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        id: setup-python
        with:
          python-version: "3.11"
      - name: Install Python deps
        run: |
          "${{ steps.setup-python.outputs.python-path }}" -m pip install --upgrade pip sympy
          "${{ steps.setup-python.outputs.python-path }}" -c "import sys, sympy; print(sys.executable); print(sympy.__version__)"
      - uses: julia-actions/setup-julia@v3
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: julia-actions/cache@v3
      - uses: julia-actions/julia-buildpkg@v1
        env:
          JULIA_CONDAPKG_BACKEND: Null
          JULIA_PYTHONCALL_EXE: ${{ steps.setup-python.outputs.python-path }}
      - uses: julia-actions/julia-runtest@v1
        env:
          JULIA_CONDAPKG_BACKEND: Null
          JULIA_PYTHONCALL_EXE: ${{ steps.setup-python.outputs.python-path }}
